---
- name: Copy file from local to remote clients
  hosts: all
  
  tasks:
  - name: Copying file 
    become: true
    copy:
     src: /home/flori/fisierdecopiat
     dest: /tmp
     owner: flori
     group: flori
     mode: 0644
