---
- name: Create and Remove file
  hosts: all
  
  tasks:
  - name: Create a directory
    file:
        path: /tmp/flori
        owner: flori
        group: flori
        mode: 770
        state: directory
  - name: Create a file in that directory
    file:
        path: /tmp/flori/jerry
        state: touch
  - name: Remove file
    file:
       path: /tmp/flori/jerry
       state: absent
